Issue73
reach4help/covidhelphub-frontend pull request #78
Opened 2022-03-01 08:43 UTC by minurajeeve

Added google login feature to the dashboard

2022-03-06 21:18 UTC, pratikmdhr requested changes
Hey @minurajeeve , nice work on the PR.. I see that you have implemented the login component as a standalone component with the login state shared with only it's child components which looks fine. Since you have used context API, i have suggested some changes, by which the login state will be available to the entire app and will be useful later. There are also some general comments related to the naming of the context file, and use of the useEffect hook  that you can look at.

2022-03-06 21:18 UTC, pratikmdhr commented on src/components/google_login/loginComponent.tsx
> +        clientId="626018378389-sfff95dsu0orjgvv7lb21dqtuu6ceai7.apps.googleusercontent.com"
you can add this as environment variable so you can use it at other places too like the logout comp..

2022-03-06 21:18 UTC, pratikmdhr commented on src/components/HomeComponent.tsx
>  // eslint-disable-next-line func-names
you should delete these

2022-03-17 07:22 UTC, minurajeeve commented on src/components/HomeComponent.tsx
> +  const value = useMemo(() => ({ loginState, setLoginState }), [loginState]);
Isn't the Home component the top-level component? If not what is the top-level component?

2022-03-18 13:59 UTC, pratikmdhr commented on src/components/HomeComponent.tsx
> +  const value = useMemo(() => ({ loginState, setLoginState }), [loginState]);
App.tsx is the top level one

2022-03-20 08:54 UTC, closed without merging

2022-03-20 08:54 UTC, minurajeeve commented
Made the necessary changes